"""initial schema

Revision ID: 13dd8b603d82
Revises: 
Create Date: 2026-09-05 17:13:23.119057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dd8b603d82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switch_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('environment', sa.Enum('demo', 'live', name='environment'), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('style', sa.Enum('trading', 'investment', name='strategystyle'), nullable=False),
    sa.Column('live_enabled', sa.Boolean(), nullable=False),
    sa.Column('approval_mode', sa.Enum('manual', 'auto_above_threshold', 'auto', name='approvalmode'), nullable=False),
    sa.Column('approval_threshold', sa.Float(), nullable=False),
    sa.Column('notify_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('books',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('environment', sa.Enum('demo', 'live', name='environment'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'environment', name='uq_book_strategy_env')
    )
    op.create_table('strategy_config_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'promoted', name='configversionstatus'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('config_version_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('universe', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('starting_capital', sa.Float(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['strategy_config_versions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('config_version_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('environment', sa.Enum('demo', 'live', name='environment'), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('signal_type', sa.Enum('entry', 'exit', name='signaltype'), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('exit_plan', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'auto_approved', 'pending_approval', 'approved', 'rejected', 'expired', 'executed', name='signalstatus'), nullable=False),
    sa.Column('requires_manual_approval', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('counterfactual_outcome', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['config_version_id'], ['strategy_config_versions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('screening', 'research', name='insighttier'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('environment', sa.Enum('demo', 'live', name='environment'), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'filled', 'failed', name='orderstatus'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('insights')
    op.drop_table('signals')
    op.drop_table('backtest_runs')
    op.drop_table('strategy_config_versions')
    op.drop_table('books')
    op.drop_table('strategies')
    op.drop_table('kill_switch_events')
    # ### end Alembic commands ###
