"""confidence calibration table

Revision ID: 462b9dcc2893
Revises: 13dd8b603d82
Create Date: 2026-09-05 18:53:56.724478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462b9dcc2893'
down_revision: Union[str, Sequence[str], None] = '13dd8b603d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confidence_calibrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('config_version_id', sa.String(), nullable=False),
    sa.Column('buckets', sa.JSON(), nullable=False),
    sa.Column('source_backtest_run_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['strategy_config_versions.id'], ),
    sa.ForeignKeyConstraint(['source_backtest_run_id'], ['backtest_runs.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'config_version_id', name='uq_calibration_strategy_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confidence_calibrations')
    # ### end Alembic commands ###
