#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Run this from the repo root (it shells into backend/ and infra/gcp/ as needed).
# Values captured here are stored in backend/.env — the same file the app itself reads locally.
ENV_FILE="${ENV_FILE:-backend/.env}"

banner "Loom deployment: Vercel + Neon + Cloud Run + Cloud Scheduler"

# ── Stage 1: GCP CLI + project ─────────────────────────────────────────────
stage "GCP: authenticate and pick a project"
say "Everything backend-side (Cloud Run, Cloud Scheduler, Secret Manager) lives in one GCP project."
if ! command -v gcloud >/dev/null 2>&1; then
  warn "gcloud CLI not found. Install it first: https://cloud.google.com/sdk/docs/install"
  open_url "https://cloud.google.com/sdk/docs/install"
  pause "Press Enter once gcloud is installed and on your PATH"
fi
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" 2>/dev/null | grep -q .; then
  step "Not logged in yet — running 'gcloud auth login' (opens a browser)."
  gcloud auth login
fi
note "current account: $(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null)"
open_url "https://console.cloud.google.com/projectcreate"
step "Create a project if you don't have one yet for Loom (billing must be enabled on it)."
ask GCP_PROJECT_ID "GCP project ID:"
ask GCP_REGION "GCP region [Enter for europe-west2]:"
GCP_REGION="${GCP_REGION:-europe-west2}"
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_REGION "$GCP_REGION"
gcloud config set project "$GCP_PROJECT_ID" >/dev/null

# ── Stage 2: Neon ───────────────────────────────────────────────────────────
stage "Neon: database"
say "Loom's schema is created by Alembic migrations later — nothing to configure in Neon itself"
say "beyond creating the project and grabbing its connection string."
open_url "https://console.neon.tech"
step "Create a project (or use an existing one), then copy its connection string"
step "(Dashboard → Connection Details → the postgresql:// URL)."
ask NEON_RAW_URL "Paste the connection string (starts postgresql://):"
DATABASE_URL="${NEON_RAW_URL/postgresql:\/\//postgresql+psycopg://}"
write_env DATABASE_URL "$DATABASE_URL"
note "rewrote the scheme to postgresql+psycopg:// (the driver Loom's SQLAlchemy setup expects)"

# ── Stage 3: Trading 212 ────────────────────────────────────────────────────
stage "Trading 212: API key + secret"
say "A T212 account issues ONE key+secret pair total — it authenticates against both"
say "demo.trading212.com and live.trading212.com; the base URL picks the environment, not the"
say "credential. Generate it once here, it covers both."
warn "I don't have a guaranteed deep link to T212's key-generation page — opening the app;"
warn "look for Settings → API (Beta) or similar. If you can't find it, check T212's own docs."
open_url "https://www.trading212.com/login"
step "Log in, find the API key section, choose 'New API key', and generate one."
step "Copy the key, then copy the secret — the secret is shown once, at creation time."
ask T212_API_KEY "Paste the T212 API key:"
ask_secret T212_API_SECRET "Paste the T212 API secret:"
write_env T212_API_KEY "$T212_API_KEY"
write_env T212_API_SECRET "$T212_API_SECRET"

# ── Stage 4: LLM provider keys ──────────────────────────────────────────────
stage "LLM providers: Anthropic + Google (Gemini)"
say "Anthropic powers the paid, user-triggered deep-research tier and the Ask feature."
open_url "https://console.anthropic.com/settings/keys"
step "Create a key and copy it."
ask_secret ANTHROPIC_API_KEY "Paste the Anthropic API key:"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"

say "Google (Gemini) powers the free, automatic screening research pass. Optional — leave blank"
say "to skip it for now; Loom falls back to a no-op generator with nothing set."
if confirm "Set up a Google API key now?"; then
  open_url "https://aistudio.google.com/apikey"
  step "Create an API key and copy it."
  ask_secret GOOGLE_API_KEY "Paste the Google API key:"
  write_env GOOGLE_API_KEY "$GOOGLE_API_KEY"
else
  GOOGLE_API_KEY=""
  note "skipped — GOOGLE_API_KEY left unset"
fi

# ── Stage 5: Provision GCP infrastructure ───────────────────────────────────
stage "Provision GCP infrastructure"
say "About to run infra/gcp/setup.sh — creates real, billable cloud resources:"
say "Artifact Registry, two service accounts, five empty Secret Manager secrets, the Cloud Run"
say "Service, four Cloud Run Jobs, and Cloud Scheduler entries. Safe to re-run (idempotent)."
if confirm "Run infra/gcp/setup.sh against project $GCP_PROJECT_ID now?"; then
  PROJECT_ID="$GCP_PROJECT_ID" REGION="$GCP_REGION" ./infra/gcp/setup.sh
else
  warn "every later stage needs the secrets/infra this creates — stopping here."
  note "run it yourself, then re-run this wizard (it remembers what you've already entered):"
  note "  PROJECT_ID=$GCP_PROJECT_ID REGION=$GCP_REGION ./infra/gcp/setup.sh"
  exit 0
fi
CLOUD_RUN_URL=$(gcloud run services describe loom-api --region "$GCP_REGION" --project "$GCP_PROJECT_ID" --format='value(status.url)' 2>/dev/null || true)
if [[ -n "$CLOUD_RUN_URL" ]]; then
  write_env CLOUD_RUN_SERVICE_URL "$CLOUD_RUN_URL"
  note "Cloud Run Service URL: $CLOUD_RUN_URL (needed again in stage 9)"
fi

# ── Stage 6: Fill the real secret values ────────────────────────────────────
stage "Fill Secret Manager with the real values"
say "infra/gcp/setup.sh created five secrets empty. Filling them now with what you've already"
say "entered in stages 2-4 — nothing to re-type."
printf '%s' "$DATABASE_URL" | gcloud secrets versions add loom-database-url --data-file=- --project "$GCP_PROJECT_ID"
printf '%s' "$T212_API_KEY" | gcloud secrets versions add loom-t212-api-key --data-file=- --project "$GCP_PROJECT_ID"
printf '%s' "$T212_API_SECRET" | gcloud secrets versions add loom-t212-api-secret --data-file=- --project "$GCP_PROJECT_ID"
printf '%s' "$ANTHROPIC_API_KEY" | gcloud secrets versions add loom-anthropic-api-key --data-file=- --project "$GCP_PROJECT_ID"
printf '%s' "$GOOGLE_API_KEY" | gcloud secrets versions add loom-google-api-key --data-file=- --project "$GCP_PROJECT_ID"
say "Redeploying the Cloud Run Service so it picks up these new secret versions"
say "(Jobs read :latest fresh on every run — they don't need this)."
gcloud run services update loom-api --region "$GCP_REGION" --project "$GCP_PROJECT_ID" >/dev/null
note "done"

# ── Stage 7: Database migrations ────────────────────────────────────────────
stage "Run database migrations"
say "Applying Loom's schema to the real Neon database."
if command -v alembic >/dev/null 2>&1 || [[ -x backend/.venv/bin/alembic ]]; then
  ( cd backend && DATABASE_URL="$DATABASE_URL" alembic upgrade head )
else
  warn "alembic not found on PATH — run manually:"
  note "  cd backend && DATABASE_URL=\"$DATABASE_URL\" alembic upgrade head"
  SKIPPED+=("alembic upgrade head (run it manually — see above)")
fi

# ── Stage 8: GitHub Actions wiring ──────────────────────────────────────────
stage "GitHub Actions: deploy secrets"
say "Creating a deploy-scoped service account so CI can build/push/deploy without using your"
say "personal credentials."
DEPLOY_SA="loom-deployer@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
gcloud iam service-accounts describe "$DEPLOY_SA" --project "$GCP_PROJECT_ID" >/dev/null 2>&1 || \
gcloud iam service-accounts create loom-deployer --display-name="Loom CI/CD deployer" --project "$GCP_PROJECT_ID"
for ROLE in roles/run.admin roles/artifactregistry.writer roles/iam.serviceAccountUser; do
  gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
    --member="serviceAccount:${DEPLOY_SA}" --role="$ROLE" --condition=None >/dev/null
done
KEY_FILE=$(mktemp)
gcloud iam service-accounts keys create "$KEY_FILE" --iam-account="$DEPLOY_SA" --project "$GCP_PROJECT_ID" >/dev/null
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh CLI not ready — install/auth it, then set these repo secrets yourself:"
  note "  gh secret set GCP_PROJECT_ID --body \"$GCP_PROJECT_ID\""
  note "  gh secret set GCP_DEPLOY_SA_KEY < $KEY_FILE"
  note "  gh secret set DATABASE_URL --body \"$DATABASE_URL\""
  warn "the downloaded key is at $KEY_FILE — delete it once you've used it"
  SKIPPED+=("GitHub secrets GCP_PROJECT_ID, GCP_DEPLOY_SA_KEY, DATABASE_URL (see above)")
else
  set_secret GCP_PROJECT_ID "$GCP_PROJECT_ID"
  gh secret set GCP_DEPLOY_SA_KEY < "$KEY_FILE" >/dev/null && \
    { WRITTEN_SECRET+=("GCP_DEPLOY_SA_KEY"); printf '  %s✓ set%s GitHub secret GCP_DEPLOY_SA_KEY\n' "$GREEN" "$RESET"; }
  set_secret DATABASE_URL "$DATABASE_URL"
  rm -f "$KEY_FILE"
  note "deleted the local copy of the deploy key"
fi

# ── Stage 9: Vercel ──────────────────────────────────────────────────────────
stage "Vercel: frontend"
say "Vercel needs one thing beyond auto-detecting the Next.js app: the Cloud Run API URL."
open_url "https://vercel.com/new"
step "Import this repo, set the project root directory to 'frontend'."
step "Under Environment Variables, add:"
if [[ -n "${CLOUD_RUN_URL:-}" ]]; then
  note "  NEXT_PUBLIC_API_BASE_URL = $CLOUD_RUN_URL"
else
  note "  NEXT_PUBLIC_API_BASE_URL = <the Cloud Run Service URL from stage 5>"
fi
step "Deploy. Every future push to the connected branch redeploys automatically."
confirm "Done in the Vercel dashboard?" || warn "come back to this once you have"
# ──────────────────────────────────────────────────────────────────────────

finish
